version: "3.9"
services:
  aarch64-base:
    build: 
      context: ../
      dockerfile: containers/base/Dockerfile
      args:
        IMAGE_NAME: arm64v8/ubuntu
    network_mode: host
    volumes: 
      - ../:/home/cu-robotics/buff-code
    image: curobotics/buffbox:aarch64-base
  x86_64-base:
    build: 
      context: ../
      dockerfile: containers/base/Dockerfile
      args:
        IMAGE_NAME: ubuntu:18.04
    network_mode: host
    volumes: 
      - ../:/home/cu-robotics/buff-code
    image: curobotics/buffbox:x86_64-base
  aarch64-dev:
    build: 
      context: ../
      dockerfile: containers/dev/Dockerfile
      args:
        IMAGE_NAME: curobotics/buffbox:aarch64-base
    network_mode: host
    volumes: 
      - ../:/home/cu-robotics/buff-code
      - /tmp/.X11-unix
    environment: 
      - DISPLAY
    image: curobotics/buffbox:aarch64-dev
  x86_64-dev:
    build:
      context: ../
      dockerfile: containers/dev/Dockerfile
      args:
        IMAGE_NAME: curobotics/buffbox:x86_64-base
    network_mode: host
    volumes: 
      - ../:/home/cu-robotics/buff-code
      - /tmp/.X11-unix
    environment: 
      - DISPLAY
    image: curobotics/buffbox:x86_64-dev
  cross-build:
    build:
      context: ../
      dockerfile: containers/dev/Dockerfile
      args:
        IMAGE_NAME: curobotics/buffbox:aarch64-dev
    volumes: 
      - ../:/home/cu-robotics/buff-code
      - /tmp/.X11-unix
    image: curobotics/buffbox:aarch64-dev
    command: /home/cu-robotics/buff-code/buffpy/bin/buffpy --build rust

