<<<<<<< HEAD
[package]
name = "echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosrust = "0.9"
serde = "1.0.127"
rosrust_msg = "0.1"
env_logger = "0.9.0"
=======
[package]
name = "echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosrust = "0.9"
hidapi = "1.4.1"
serde = "1.0.127"
rosrust_msg = "0.1"
env_logger = "0.9.0"
>>>>>>> 0d6ccaacf964cb391ab0206cf7f532effdba410f
serde_derive = "1.0.127"