dr16:
  group: "receiver"
  options: [0]

mpu6050:
  group: "imu"
  options: [1]

fl_drive:
  group: "can"
  options: [1, 0, 0]
fl_steer:
  group: "can"
  options: [1, 0, 1]
rr_steer:
  group: "can"
  options: [1, 2, 1]