buff_rust:
  debug: True
  files: ['comms_node', controller_node]


rqt_plot:
  files: ['rqt_plot']
  package: 'rqt_plot'

robot: 'infantry'

can:
#   name, can bus, message, offset
  - ['fl_drive', '1', '0', '0']
  - ['fl_steer', '1', '0', '1']
  - ['gimbal_pan', '2', '2', '2']
  - ['feeder', '2', '0', '1']
  - ['golf_motor1', '2', '0', '0']
  - ['golf_motor2', '2', '1', '1']

fl_steer_gains:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]

fl_drive_gains:
  - [100.0, 0.0, 0.0]
  - [0.000025, 0.01, 0.0004]

gimbal_pan_gains:
  - [0.0, 0.0, 0.0]
  - [0.000018, 0.0, 0.0004]

feeder_gains:
  - [0.0, 0.0, 0.0]
  - [0.003, 0.0, 0.0]

golf_motor1_gains:
  - [0.0, 0.0, 0.0]
  - [0.00002, 0.0, 0.0]

golf_motor2_gains:
  - [0.0, 0.0, 0.0]
  - [0.00002, 0.0, 0.0]