buff_rust:
  debug: True
  files: ['comms_node', controller_node]


rqt_plot:
  files: ['rqt_plot']
  package: 'rqt_plot'

robot: 'infantry'

can:
  - ["fl_drive", "1", "0", "0"]
  - ["fl_steer", "1", "0", "1"]
  - ["gm6020_left", "2", "2", "2"]
  - ["gm6020_right", "2", "2", "1"]
  - ["feeder", "2", "0", "1"]

fl_steer_gains:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]

fl_drive_gains:
  - [100.0, 0.0, 0.0]
  - [0.000025, 0.01, 0.0004]

feeder_gains:
  - [0.0, 0.0, 0.0]
  - [0.003, 0.0, 0.0]

gm6020_left_gains:
  - [100.0, 0.0, 0.0]
  - [0.0003, 0.0, 0.005]

gm6020_right_gains:
  - [100.0, 0.0, 0.0]
  - [0.0003, 0.0, 0.0]


