# The buff stuff
buff_rust:
  files: [comms_node, device_node, locomotion_node]

# Maybe some kind of option to shut this down via cmdline
# rqt_plot:
#   files: [rqt_plot]
#   package: rqt_plot

# Unused atm (should be just isn't)
robot_name: penguin
robot_type: infantry
inertial_feedback: empty_topic
state_feedback: joystick_input

# Defines the sensor index for
# HID packets. String is the topic
sensor_index:
  - mpu6050
  - dr16

# This defines the indices of all the motors
motor_index:
  - xn_drive
  - xp_drive
  - yn_drive
  - yp_drive
  - yaw
  - pitch
  - feeder

# Uses the motor indices to determine a can
# packet index
motor_can_index:
  # [can bus, message type, motor offset]
  - [2, 1, 2]
  - [2, 1, 1]
  - [2, 0, 2]
  - [1, 0, 3]
  - [2, 2, 2]
  - [2, 2, 1]
  - [2, 0, 1]
  
# Motor controls are a linear combo
# of the state. U = -Kx
state_control_law: # K
  - [0.0,   0.0,   -1.0,    0.0,    1.0,    0.0,    0.0]
  - [0.0,   0.0,    1.0,    0.0,    1.0,    0.0,    0.0]
  - [0.0,   0.0,    0.0,   -1.0,    1.0,    0.0,    0.0]
  - [0.0,   0.0,    0.0,    1.0,    1.0,    0.0,    0.0]
  - [0.0,   0.0,    0.0,    0.0,   -6.0,    1.0,    0.0]
  - [0.0,   0.0,    0.0,    0.0,    0.0,    0.0,    1.0]
  - [1.0,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0]


position_control_index:
  - yaw
  - pitch
  - feeder

# Gains for the motor at
# the same index in the
# control index
position_control_gains:
  - [  0.0003,    0.0,    0.0,  0.000025,    0.01,  0.0004]
  - [     0.0,    0.0,    0.0,  0.000025,    0.01,  0.0004]
  - [   0.003,    0.0,    0.0,  0.000025,    0.01,  0.0004]

velocity_control_index:
  - xn_drive
  - xp_drive
  - yn_drive
  - yp_drive

velocity_control_gains:
  - [0.000025,  0.0,    0.0]
  - [0.000025,  0.0,    0.0]
  - [ 0.00035,  0.0, 0.0002]
  - [0.000025,  0.0,    0.0]


