buff_rust:
  debug: True
  files: ['comms_node', controller_node]


robot: 'infantry'

can:
  - ["fl_drive", "1", "0", "0"]
  - ["fl_steer", "1", "0", "1"]
  - ["gimbal_pan", "1", "2", "1"]

fl_steer_gains:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]

fl_drive_gains:
  - [100.0, 0.0, 0.0]
  - [0.000025, 0.01, 0.0004]

gimbal_pan_gains:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]