buff_rust:
  debug: True
  files: ['comms_node', controller_node]


robot: 'infantry'

can:
  - ["fl_drive", "1", "0", "0"]
  - ["fl_steer", "1", "0", "1"]
  - ["gimbal_pan", "2", "2", "2"]
  - ["GM6020", "2", "2", "1"]
  - ["feeder", "2", "0", "1"]

fl_steer_gains:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]

fl_drive_gains:
  - [100.0, 0.0, 0.0]
  - [0.000025, 0.01, 0.0004]

gimbal_pan_gains:
  - [0.0, 0.0, 0.0]
  - [0.00003, 0.0, 0.0]

feeder_gains:
  - [0.0, 0.0, 0.0]
  - [0.003, 0.0, 0.0]

GM6020_gains:
  - [0.0, 0.0, 0.0]
  - [0.0000025, 0.01, 0.0004]

