devices:
  DR16:
    group: receiver
    key: D
    options: [0]
    with_ros: false
    input_size: 6
    output_size: 0
  MPU6050:
    group: imu
    key: I
    options: [1]
    with_ros: false
    input_size: 6
    output_size: 0
  FL_STEER:
    group: motor
    key: M
    options: [2, 0, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  FR_STEER:
    group: motor
    key: M
    options: [2, 1, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  RR_STEER:
    group: motor
    key: M
    options: [2, 2, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  RL_STEER:
    group: motor
    key: M
    options: [2, 3, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  FL_DRIVE:
    group: motor
    key: M
    options: [2, 4, 1]
    with_ros: false
    input_size: 3
    output_size: 4
  FR_DRIVE:
    group: motor
    key: M
    options: [2, 5, 1]
    with_ros: false
    input_size: 3
    output_size: 4
  RR_DRIVE:
    group: motor
    key: M
    options: [2, 6, 1]
    with_ros: false
    input_size: 3
    output_size: 4
  RL_DRIVE:
    group: motor
    key: M
    options: [2, 7, 1]
    with_ros: false
    input_size: 3
    output_size: 4