devices:
  dr16:
    group: receiver
    key: D
    options: [0]
    with_ros: false
    input_size: 6
    output_size: 0
  mpu6050:
    group: imu
    key: I
    options: [1]
    with_ros: false
    input_size: 6
    output_size: 0
  fl_steer:
    group: motor
    key: M
    options: [2, 0, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  fr_steer:
    group: motor
    key: M
    options: [2, 1, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  rr_steer:
    group: motor
    key: M
    options: [2, 2, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  rl_steer:
    group: motor
    key: M
    options: [2, 3, 0]
    with_ros: false
    input_size: 3
    output_size: 4
  fl_drive:
    group: motor
    key: M
    options: [2, 4, 1]
    with_ros: false
    input_size: 3
    output_size: 4
  fr_drive:
    group: motor
    key: M
    options: [2, 5, 1]
    with_ros: false
    input_size: 3
    output_size: 4
  rr_drive:
    group: motor
    key: M
    options: [2, 6, 1]
    with_ros: false
    input_size: 3
    output_size: 4
  rl_drive:
    group: motor
    key: M
    options: [2, 7, 1]
    with_ros: true
    input_size: 3
    output_size: 4