#! /usr/bin/env python3

import os 
import sys
import time
import yaml
import rospy
import signal
import roslaunch
import subprocess as sb

def load_config(target_path):
	"""
		Loda the target system config file.
		Now featuring recursive inheritance!
		PARAMS:
			file: The overwriting conf data
		RETURNS:
			case 0: empty dictionary
			case 1: the parent data (dict)
			case 2: the parent updated with the child (dict)
	"""
	if not os.path.exists(target_path):
		print(f'Could not find data dir {target_path}: ...')
		return {}

	with open(os.path.join(target_path, 'nodes.yaml'), 'r') as f:
		data = yaml.safe_load(f)

	# if 'FROM' in data:
	# 	parent = os.path.join(os.getenv('PROJECT_ROOT'), 'buffpy', 'config', 'system', data['FROM'])
	# 	if not os.path.exists(parent):
	# 		parent = os.path.join(os.getenv('PROJECT_ROOT'), 'buffpy', 'config', 'robots', data['FROM'])

	# 	parentData = load_config(file=parent)

	# 	data = overwrite_conf(data, parentData)

	if not data is None:
		data['self'] = target_path

	return data

def parse_target(robot):
	""" 
		Get target_path and config if they exist, all
		input checking debugging gets done here before launch
		PARAMS:
			args: list of strings, [file, args] args can be None
			projectRoot: filepath, root of the project
		RETURN:
			target_path: filepath, the target (yaml or py)
			target_args: args for a python script
			config: config data (dict), config for a system
	"""
	projectRoot = os.getenv('PROJECT_ROOT')	# path to project root

	config = None 
	target_args = []
	target_path = None

	target_path = os.path.join(projectRoot, 'buffpy', 'data', 'robots', robot)

	config = load_config(target_path)	# None if no config

	if config is None:
		print(f'No data in {target_path}')

	else:
		print(f'Targeting: {target_path}')

	return target_path, target_args, config

def launch_system(robot, target_path, nodes):
	"""
		This wil launch all nodes and roscore. 
		launches core process with subprocess.Popen 
		systems are launched with the usage below
		rosrun package program args=[debug, config, topics...]
		PARAMS:
			target_path: filepath, to yaml
			config: load configuration (dict)
		RETURNS:
			core_process: subprocess obj, the core process
			pool: list of roslaunch processes
	"""
	
	args = []
	pool = []
	params = {}
	respawn = []
	commands = []
	cmd = 'roscore'
	core_process = None

	project_root = os.getenv('PROJECT_ROOT')
		
	# Set nodes and package

	print(f'System Definition:\n{yaml.dump(nodes, allow_unicode=True, default_flow_style=False)}\n')

	# Cant spawn pool without nodes
	if nodes is None:
		print(f'Missing NODES in config file {target_path}')

	else:
		namespace = '/buffbot'
		params['robot_name'] = robot

		command_string = f"rosrun xacro xacro {os.path.join(project_root, f'buffpy/data/robots/{robot}/buffbot.xacro')}"
		robot_description = sb.check_output(command_string, shell=True, stderr=sb.STDOUT)
		params['robot_description'] = robot_description.decode()

		# launch core
		core_process = sb.Popen(cmd, stdout=sb.PIPE, stderr=sb.PIPE)

		launch = roslaunch.scriptapi.ROSLaunch()
		launch.start()

		rospy.set_param(f'{namespace}', params)

		# load and launch each node in the config
		for name in nodes:
			node = nodes[name]
			if isinstance(node, str) or isinstance(node, int):
				continue

			if 'package' in node:
				package = node['package']
			else:
				package = 'buffpy'

			if 'args' in node:
				# can use args tag to send args to nodes
				args = []
				for arg in node['args']:

					# find any env vars
					split1 = arg.split('{')

					n = len(split1) // 2

					if n == 0:
						args.append(arg)
						continue

					split = ''

					for i in range(n):
						split2 = split1[(i * 2) + 1].split('}')
						split += split1[2 * i][:-1] + os.getenv(split2[0]) + split2[1]

					args.append(split)

			if 'required' in node:
				required = node['required']
			else:
				required = False

			# launch the process and add it to the pool
			if 'files' in node:
				for program in node['files']:
					cmd = ['rosrun', package, program] + args
					process = sb.Popen(cmd)
					commands.append(cmd)
					pool.append(process)
					respawn.append(required)


	return core_process, pool, respawn, commands

def spin(robot, config, target_path, target_args):
	"""
		initialize the run and launch
		loop and wait for user kill or core to finish
		PARAMS:
			config: a python script or system config file (yaml)
			target_path: the targetfile to launch or roscore
			target_args: arguments for the target file
	"""

	# target path is essential for launching. If it is empty
	# there was an error and the program should exit
	if target_path is None or config is None:
		print(f'Failed to load target: {target_path}')
		exit(0)

	pool = None
	launch = None
	core_process = None
	# Try to catch user kill and other errors
	try: 
		core_process, pool, respawn, commands = launch_system(robot, target_path, config)
		# core_process is the core process we are trying to spawn (python script or roscore)
		# if it fails there is no point in spinning
		if core_process is None: 
			print('Launching target core failed :(')
			exit(0)

		# this hanldes user kill (available after spawn & in the run space below)
		# this will loop until an interrupt or the core dies.
		while core_process.poll() is None:
			# if output/errors print them
			# mesg = core_process.communicate()
			# if mesg[0]:
			# 	print(mesg[0].decode('utf-8')) # this will force us to use rospy.log to print info I think
			# if mesg[1]:
			# 	print(mesg[1].decode('utf-8')) # output is sent from program to roscore then printed here

			# restart processes with the respawn flag
			if not pool is None:
				for i, proc in enumerate(pool):
					if not proc.poll() is None and proc.returncode != 0 and respawn[i]:
						print(f'{commands[i]} died: {proc.returncode}')
						print(f'restarting {commands[i]}')
						pool[i] = sb.Popen(commands[i])

	except KeyboardInterrupt as e:
		print(e)
		print('Terminate Recieved:...')

	except Exception as e:
		print(e)
		print('Killed due to error')

	if not pool is None:
		for i,proc in enumerate(pool):
			proc.terminate()

	if not core_process is None:
		core_process.terminate()

def main(args):
	"""
		Launch all relevant pool.
		See wiki for input usage
	"""
	if len(args) < 2:
		robot = 'penguin'
	else:
		robot = args[1]

	# parse the input 
	target_path, target_args, config = parse_target(robot)

	# spin till finished
	spin(robot, config, target_path, target_args) 

	print('RUN finished')
		

if __name__ == '__main__':
	main(sys.argv)