DEBUG:
  True
  

TOPICS:
  IMAGE: 'image_raw'
  IMAGE_DEBUG: 'image_debug'
  DETECTION_PIXEL: 'pixel_detection'



NODES:
  BUFFNET: # spawns our detector node
    FILES: ['buffnet.py']
    PACKAGE: 'buffpy'
    REQUIRED: False
  CAMERA:
    CONFIG: 'camera_settings.yaml'
    FILES: ['data_streamer.py'] # ['mds_camera.py'] #
    PACKAGE: 'buffpy'
  MODEL:
    CONFIG: 'model_settings.yaml'
  RQT_GUI:    # Opens an rqt_graph
    FILES: ['rqt_gui']
    PACKAGE: 'rqt_gui'
    ARGS:
      - '--perspective-file ${PROJECT_ROOT}/buffpy/config/data/buff_view.perspective'
