DEBUG: True
FROM: 'live.yaml'

TOPICS:
  TARGET_MAP: 'target_map'
  IMAGE_DEBUG: 'image_debug'
  TRACKING_ERROR: 'tracking_error'
  DETECTION_WORLD: 'world_detection'
  

NODES:
  # ROSBAGGER:    # This will record all system runs and allow us to play them back
  #   FILE:
  #     'record'
  #   PACKAGE:
  #     'rosbag'
  #   ARGS:       # -a record all -x ignore -o output prefix
  #     - '-a'
  #     - '-x /rosout'
  #     - '-o /home/cu-robotics/buff-code/data/'
  LUXONIS:
    REQUIRED: False
  TRACKER:     # spawns our tracker node
    FILES: ['target_map.py']
  RQT_GUI:    # Opens an rqt_graph
    FILES: ['rqt_gui']
    PACKAGE: 'rqt_gui'
    ARGS:
      - '--perspective-file ${PROJECT_ROOT}/buffpy/config/data/buff_view.perspective'


