DEBUG:
  False
  

TOPICS:
  IMAGE: 'image_raw'
  GIMBAL_STATE: 'gimbal_state'
  SERIAL_OUT: 'serial_write'
  DETECTION_PIXEL: 'image_detection'
  DETECTION_WORLD: 'world_detection'


NODES:
  # ROSBAGGER:    # This will record all system runs and allow us to play them back
  #   FILE: 'record'
  #   PACKAGE: 'rosbag'
  #   ARGS:       # -a record all  -x ignore -o output prefix
  #     ['-a', '-x /rosout', '-o /home/cu-robotics/buff-code/data/']
  LUXONIS: # spawns our detector node
    FILES: ['luxnet.py']
    PACKAGE: 'buffpy'
    REQUIRED: True
  TRACKER:     # spawns our tracker node
    FILES: ['deadreckon_tracer.py', 'projector.py']
    CONFIG: 'tracker_settings.yaml'
    PACKAGE: 'buffpy'
  SERIAL:
    FILES: ['serial_layer.py']
    CONFIG: 'serial_settings.yaml'
    PACKAGE: 'buffpy'

  CAMERA:
    CONFIG: 'camera_settings.yaml'
  MODEL:
    CONFIG: 'model_settings.yaml'
