DEBUG: True

TOPICS:
  IMU: 'imu'
  DR16: 'remote_input'
  HID_OUTPUT: 'teensy_commands'
  FL_SWERVE_STEER: 'front_left_swerve_steer'
  FR_SWERVE_STEER: 'front_right_swerve_steer'
  RR_SWERVE_STEER: 'rear_right_swerve_steer'
  RL_SWERVE_STEER: 'rear_left_swerve_steer'
  FL_SWERVE_DRIVE: 'front_left_swerve_drive'
  FR_SWERVE_DRIVE: 'front_right_swerve_drive'
  RR_SWERVE_DRIVE: 'rear_right_swerve_drive'
  RL_SWERVE_DRIVE: 'rear_left_swerve_drive'
  REMOTE_CONTROL: 'rc_input'

NODES:
  RUST:
    FILES: ['buff_rust']
  
DEVICES:
    LUT: [IMU, DR16,
      FL_SWERVE_STEER, 
      FR_SWERVE_STEER, 
      RR_SWERVE_STEER, 
      RL_SWERVE_STEER, 
      FL_SWERVE_DRIVE, 
      FR_SWERVE_DRIVE, 
      RR_SWERVE_DRIVE, 
      RL_SWERVE_DRIVE]

    IMU:
      TYPE: 'imu'
      ENABLED: True

    DR16:
      TYPE: 'dr16'
      ENABLED: True

    FL_SWERVE_STEER:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    FR_SWERVE_STEER:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    RR_SWERVE_STEER:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    RL_SWERVE_STEER:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    FL_SWERVE_DRIVE:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    FR_SWERVE_DRIVE:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    RR_SWERVE_DRIVE:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0

    RL_SWERVE_DRIVE:
      TYPE: 'motor'
      ENABLED: False
      CANBUS: 2
      MOTORID: 0
