DEBUG: False
  

TOPICS:
  IMAGE: 'image_raw'
  GIMBAL_STATE: 'gimbal_state'
  SERIAL_OUT: 'serial_write'
  DETECTION_RED: 'red_detection'
  DETECTION_BLUE: 'blue_detection'
  DETECTION_PIXEL: 'image_detection'


NODES:
  # ROSBAGGER:    # This will record all system runs and allow us to play them back
  #   FILE: 'record'
  #   PACKAGE: 'rosbag'
  #   ARGS:       # -a record all  -x ignore -o output prefix
  #     ['-a', '-x /rosout', '-o /home/cu-robotics/buff-code/data/']

  SERIAL:
    FILES: ['serial_layer.py']
    CONFIG: 'serial_settings.yaml'

  BLUE_TRACKER:     # spawns our tracker node
    FILES: ['deadreckon_tracer.py']
    CONFIG: None
    DETECTION_TOPIC: 'DETECTION_BLUE'

  TRACKER:
    CONFIG: 'tracker_settings.yaml'
  MODEL:
    CONFIG: 'model_settings.yaml'
  CAMERA:
    CONFIG: 'camera_settings.yaml'
