DEBUG:
  True
  

TOPICS:
  RAW_IMG:
    'image_raw'


NODES:

  SERIAL:     # spawns our camera streamer
    FILE:
      'serial_layer.py'
    CONFIG:
      'default_serial.yaml'
    PACKAGE:
      'buffpy'
    REQUIRED:
      'yes'  # can be anything