DEBUG: True
  

TOPICS:
  IMAGE: 'image_raw'
  GIMBAL_STATE: 'gimbal_state'
  SERIAL_OUT: 'serial_write'
  DETECTION_RED: 'red_detection'
  DETECTION_BLUE: 'blue_detection'
  DETECTION_PIXEL: 'image_detection'
  TARGET_MAP: 'target_map'
  IMAGE_DEBUG: 'image_debug'
  TRACKING_ERROR: 'tracking_error'
  DETECTION_WORLD: 'world_detection'

NODES:
  RED_TRACKER:     # spawns our tracker node
    FILES: ['deadreckon_tracer.py']
    CONFIG: None
    DETECTION_TOPIC: 'DETECTION_RED'

  MODEL:
    CONFIG: 'model_settings.yaml'
  CAMERA:
    CONFIG: 'camera_settings.yaml'
  TRACKER:
    CONFIG: 'tracker_settings.yaml'