# if debug is true:
# print the detections,
# save them periodically

# random_noise, sine
DEBUG: True

TOPICS:
    DETECTED: "detected_object"
    TARGET: "target"
    ERROR: "tracking_error"

NODES:
    # demo detector will publish 2d coords at 30fps to detected_object
    # goal of the tracker is to upsample, predict and publish these detections to tracker

    CAMERA: # spawn detector
        FILE: "tracker_demo_detector.py"
        TOPICS:
          - "DETECTED"
        CONFIG: "tracker_demo_config.yaml"
        PACKAGE: "buffpy"
    TRACKER: # spawns our tracker node
        FILE: "tracker.py"
        TOPICS:
            PUBLISH:
              - "TARGET"
              - "ERROR"
            SUBSCRIBE:
              - "DETECTED"

        PACKAGE: "buffpy"
