DEBUG:
  True
  

TOPICS:
  IMAGE: 'image_raw'
  GIMBAL_STATE: 'gimbal_state'
  SERIAL_OUT: 'serial_write'
  DETECTION_PIXEL: 'image_detection'
  DETECTION_WORLD: 'world_detection'


NODES:
  # ROSBAGGER:    # This will record all system runs and allow us to play them back
  #   FILE: 'record'
  #   PACKAGE: 'rosbag'
  #   ARGS:       # -a record all  -x ignore -o output prefix
  #     ['-a', '-x /rosout', '-o /home/cu-robotics/buff-code/data/']
  BUFFNET: # spawns our detector node
    FILES: ['buffnet.py']
    PACKAGE: 'buffpy'
    REQUIRED: True
  LUXONIS:
    FILES: []
    PACKAGE: 'buffpy'
    REQUIRED: False

  CAMERA:
    CONFIG: 'camera_settings.yaml'
    FILES: ['mds_camera.py']
    PACKAGE: 'buffpy'

