DEBUG: True
FROM: 'debug.yaml'


NODES:
  BUFFNET: # spawns our detector node
    FILES: ['buffnet.py']
    PACKAGE: 'buffpy'
    REQUIRED: False
  LUXONIS:
    FILES: []
    REQUIRED: False
  CAMERA:
    FILES: ['data_streamer.py'] # ['mds_camera.py'] #
    PACKAGE: 'buffpy'
