DEBUG: True
FROM: 'debug.yaml'


NODES:
  BUFFNET: # spawns our detector node
    FILES: ['tracker_demo_detector.py']
    PACKAGE: 'buffpy'
    REQUIRED: False
  LUXONIS:
    FILES: []
    REQUIRED: False
  CAMERA:
    FILES: [] # ['data_streamer.py'] #
    PACKAGE: 'buffpy'
