[package]
name = "buff_rust"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.0.2"
nalgebra = "0.31.1"
urdf-rs = "0.6.5"
rosrust = "0.9"
hidapi = "1.4.1"
yaml-rust = "0.4.5"
rosrust_msg = "0.1"
serde_yaml = "0.9.4"
env_logger = "0.9.0"
serde_derive = "1.0.127"
serde = {version = "1.0.127", features = ["derive", "rc"]}

[[bin]]
name = "comms_node"
path = "src/teensy_comms/node.rs"

[[bin]]
name = "controller_node"
path = "src/locomotion/node.rs"
