authors: []
blacklist: []
build_space: buffpy/debug_build
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: buffpy/debug_devel
extend_path: null
extends: null
install: false
install_space: buffpy/debug_install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
